import { UNNAMED_GROUP_PREFIX } from "./_segment-wildcards.ts";
import type { MatchedRoute, MethodData, Node, RouterContext } from "./types.ts";

export interface RouterCompilerOptions<T = any> {
  matchAll?: boolean;
  normalize?: boolean;
  serialize?: (data: T) => string;
}

/**
 * Compiles the router instance into a faster route-matching function.
 *
 * **IMPORTANT:** `compileRouter` requires eval support with `new Function()` in the runtime for JIT compilation.
 *
 * @example
 * import { createRouter, addRoute } from "rou3";
 * import { compileRouter } from "rou3/compiler";
 * const router = createRouter();
 * // [add some routes]
 * const findRoute = compileRouter(router);
 * const matchAll = compileRouter(router, { matchAll: true });
 * findRoute("GET", "/path/foo/bar");
 *
 * @param router - The router context to compile.
 */
export function compileRouter<T, O extends RouterCompilerOptions<T> = RouterCompilerOptions<T>>(
  router: RouterContext<T>,
  opts?: O,
): (
  method: string,
  path: string,
) => O["matchAll"] extends true ? MatchedRoute<T>[] : MatchedRoute<T> | undefined {
  const ctx: CompilerContext = { opts: opts || {}, router, data: [] };
  const compiled = compileRouteMatch(ctx);
  return new Function(...ctx.data!.map((_, i) => `$${i}`), `return(m,p)=>{${compiled}}`)(
    ...ctx.data!,
  );
}

/**
 * Compile the router instance into a compact runnable code.
 *
 * **IMPORTANT:** Route data must be serializable to JSON (i.e., no functions or classes) or implement the `toJSON()` method to render custom code or you can pass custom `serialize` function in options.
 *
 * @example
 * import { createRouter, addRoute } from "rou3";
 * import { compileRouterToString } from "rou3/compiler";
 * const router = createRouter();
 * // [add some routes with serializable data]
 * const compilerCode = compileRouterToString(router, "findRoute");
 * // "const findRoute=(m, p) => {}"
 */
export function compileRouterToString(
  router: RouterContext,
  functionName?: string,
  opts?: RouterCompilerOptions,
): string {
  const ctx: CompilerContext = {
    opts: opts || {},
    router,
    data: [],
    compileToString: true,
  };
  let compiled = `(m,p)=>{${compileRouteMatch(ctx)}}`;
  if (ctx.data.length > 0) {
    const dataCode = `const ${ctx.data.map((v, i) => `$${i}=${v}`).join(",")};`;
    compiled = `/* @__PURE__ */ (() => { ${dataCode}; return ${compiled}})()`;
  }
  return functionName ? `const ${functionName}=${compiled};` : compiled;
}

// ------- internal functions -------

interface CompilerContext {
  opts: RouterCompilerOptions;
  router: RouterContext<any>;
  compileToString?: boolean;
  data: string[];
}

// Trie position: either a literal character index (number) or a runtime JS expression (string).
type TriePos = number | string;

// Regex to fold "expr+K" + n into "expr+(K+n)" — pre-compiled for performance.
const _posAddRx = /^(.+)\+(\d+)$/;

// Use a switch(p[n]) over an if/else startsWith chain when there are at
// least this many distinct first characters among siblings.  Micro-benchmarks
// show the switch is slower for 2 distinct chars but faster from 3 onwards.
const SWITCH_THRESHOLD = 3;

// Use an O(1) map lookup for static routes once there are at least this many
// entries.  Below the threshold a short if/else chain with string equality is
// equally fast (V8 branch-prediction makes short chains very cheap); above it
// the map pays off and also prevents V8's AST recursion limit from being hit
// on large route tables (> ~10 k routes).
const STATIC_MAP_THRESHOLD = 10;

// Add n to a trie position. Folds consecutive numeric suffixes for clean output.
function posAdd(pos: TriePos, n: number): TriePos {
  if (n === 0) return pos;
  if (typeof pos === "number") return pos + n;
  // Simplify "expr+K" + n → "expr+(K+n)"
  const m = _posAddRx.exec(pos);
  if (m) return `${m[1]}+${Number(m[2]) + n}`;
  return `${pos}+${n}`;
}

function posStr(pos: TriePos): string {
  return String(pos);
}

// Build a JS expression that matches /key at pos and checks segment boundary.
// Approach notes (empirically validated):
//   - p.startsWith("/key", pos) outperforms per-char charCodeAt (code size + speed).
//   - A sticky-regex approach (pre-compiled regex with lastIndex set before .test())
//     benchmarked ~53% slower than startsWith+boundary due to regex-engine overhead.
//   - p[n]==="/" is shorter than p.charCodeAt(n)===47 for boundary checks.
//   - When pos is 0 the second startsWith argument is omitted (saves generated bytes).
//   - When terminal=false the trailing slash is baked into the prefix, eliminating
//     the separate boundary check (saves ~22 chars per non-terminal node).
function compileStaticSegmentCheck(pos: TriePos, key: string, terminal: boolean): string {
  const posArg = pos === 0 ? "" : `,${posStr(pos)}`;
  if (!terminal) {
    // No route ends at this exact node — path must continue with '/'.
    // Baking the slash into the prefix replaces the (len===N||p[N]==="/") check.
    return `p.startsWith(${JSON.stringify("/" + key + "/")}${posArg})`;
  }
  const endPos = posAdd(pos, 1 + key.length);
  // Boundary: path ends exactly here OR the next char is '/'
  return `p.startsWith(${JSON.stringify("/" + key)}${posArg})&&(len===${posStr(endPos)}||p[${posStr(endPos)}]==="/")`;
}

// Recursively compile a trie node into a JS code string.
// pos  – character position in `p` after the prefix matched by this node's ancestors.
// params – JS expressions for each already-captured dynamic segment value.
function compileTrieNode(
  ctx: CompilerContext,
  node: Node<any>,
  params: string[],
  pos: TriePos,
): string {
  let code = "";
  let hasIf = false;

  // 1. Method match – only for nodes reached through at least one dynamic segment.
  if (node.methods && params.length > 0) {
    const match = compileMethodMatch(ctx, node.methods, params, -1);
    if (match) {
      code += `if(len===${posStr(pos)}){${match}}`;
      hasIf = true;
    }
  }

  // 2. Static children – group by first character, then emit a switch for O(1)
  //    first-char dispatch followed by startsWith inside each case.
  //    Using a switch instead of an if/else chain keeps the generated code flat
  //    (no deeply-nested else branches) which avoids V8's parser recursion limit
  //    when there are many siblings, and gives measurably faster dispatch.
  //
  //    Array access p[n] is used instead of p.charCodeAt(n) in the switch so
  //    that case labels are readable strings ("t") rather than magic char codes
  //    (116), producing smaller generated code with no measurable perf difference.
  //
  //    Note: full-segment dispatch (extracting the segment with indexOf+slice then
  //    switching on the full string) was benchmarked but rejected — the mandatory
  //    indexOf+slice allocation per call costs ~10% on small tables and ~65% on
  //    large tables versus the charCodeAt jump-table approach.
  if (node.static) {
    // Collect entries after path compression.
    type Entry = { fullKey: string; deepNode: Node<any>; childCode: string };
    const entries: Entry[] = [];
    for (const key in node.static) {
      const child = node.static[key];

      // Path compression: absorb consecutive single-child-only static segments into
      // one startsWith call instead of nesting N separate if-blocks.
      let fullKey = key;
      let deepNode = child;
      while (deepNode.static && !deepNode.param && !deepNode.wildcard && !deepNode.methods) {
        const staticKeys = Object.keys(deepNode.static);
        if (staticKeys.length !== 1) break;
        const nextKey = staticKeys[0];
        fullKey += "/" + nextKey;
        deepNode = deepNode.static[nextKey];
      }

      const childCode = compileTrieNode(ctx, deepNode, params, posAdd(pos, 1 + fullKey.length));
      if (childCode) {
        entries.push({ fullKey, deepNode, childCode });
      }
    }

    if (entries.length > 0) {
      // Group by the first character of each key so we can emit a switch.
      const byFirstChar = new Map<string, Entry[]>();
      for (const entry of entries) {
        const ch = entry.fullKey[0];
        let group = byFirstChar.get(ch);
        if (!group) {
          group = [];
          byFirstChar.set(ch, group);
        }
        group.push(entry);
      }

      let staticCode = "";
      if (byFirstChar.size >= SWITCH_THRESHOLD) {
        // Multiple distinct first chars — switch for O(1) dispatch.
        // pos points to the leading '/', so the first key char is at pos+1.
        staticCode += `${hasIf ? "else " : ""}switch(p[${posStr(posAdd(pos, 1))}]){`;
        for (const [ch, group] of byFirstChar) {
          staticCode += `case ${JSON.stringify(ch)}:{`;
          let caseHasIf = false;
          for (const { fullKey, deepNode, childCode } of group) {
            const terminal = !!deepNode.methods || !!deepNode.wildcard || !!deepNode.param;
            const check = compileStaticSegmentCheck(pos, fullKey, terminal);
            staticCode += `${caseHasIf ? "else " : ""}if(${check}){${childCode}}`;
            caseHasIf = true;
          }
          staticCode += `break;}`;
        }
        staticCode += `}`;
        hasIf = true;
      } else {
        // All entries share the same first char — plain if-else chain is fine.
        for (const { fullKey, deepNode, childCode } of entries) {
          const terminal = !!deepNode.methods || !!deepNode.wildcard || !!deepNode.param;
          const check = compileStaticSegmentCheck(pos, fullKey, terminal);
          staticCode += `${hasIf ? "else " : ""}if(${check}){${childCode}}`;
          hasIf = true;
        }
      }

      code += staticCode;
    }
  }

  // 3. Param child – extract the next path segment with indexOf / slice.
  if (node.param) {
    const paramNode = node.param;
    const paramVar = `_p${params.length}`;
    const endVar = `_ep${params.length}`;
    const segStart = posStr(posAdd(pos, 1));
    const newParams = [...params, paramVar];

    // Optional-absent case: path ends right at `pos`, so no segment was provided.
    // Only emit a match for routes whose last param is marked optional.
    if (paramNode.methods) {
      const absentMatch = compileMethodMatch(
        ctx,
        paramNode.methods,
        [...params, "undefined"],
        -1,
        true /* absentParam */,
      );
      if (absentMatch) {
        code += `if(len===${posStr(pos)}){${absentMatch}}`;
      }
    }

    // Param-present case: there is at least one character beyond the '/' at pos.
    const isLeafParam = !paramNode.static && !paramNode.param && !paramNode.wildcard;
    if (isLeafParam) {
      // Leaf param: the param must be the last segment (no further children).
      // Avoid the let+assignment+len=== dance — just check indexOf===-1 directly.
      const methodCode = compileMethodMatch(ctx, paramNode.methods || {}, newParams, -1);
      if (methodCode) {
        code +=
          `if(len>${posStr(posAdd(pos, 1))}){` +
          `const ${endVar}=p.indexOf("/",${segStart});` +
          `if(${endVar}===-1){const ${paramVar}=p.slice(${segStart});${methodCode}}}`;
      }
    } else {
      const innerCode = compileTrieNode(ctx, paramNode, newParams, endVar);
      if (innerCode) {
        code +=
          `if(len>${posStr(posAdd(pos, 1))}){` +
          `let ${endVar}=p.indexOf("/",${segStart});` +
          `if(${endVar}===-1)${endVar}=len;` +
          `const ${paramVar}=p.slice(${segStart},${endVar});` +
          `${innerCode}}`;
      }
    }
  }

  // 4. Wildcard child – captures everything from pos+1 to end of string.
  if (node.wildcard) {
    const { wildcard } = node;
    if (wildcard.static || wildcard.param || wildcard.wildcard) {
      throw new Error("Compiler mode does not support patterns after wildcard");
    }
    if (wildcard.methods) {
      const boundary = posAdd(pos, 1);
      const wildcardParam = `p.slice(${posStr(boundary)})`;
      // Pass boundary so compileFinalMatch can guard required (named) wildcards.
      code += compileMethodMatch(ctx, wildcard.methods, params.concat(wildcardParam), -1, false, boundary);
    }
  }

  return code;
}

function compileRouteMatch(ctx: CompilerContext): string {
  let code = "";

  // Static routes: O(1) map lookup instead of an O(n) if/else chain.
  // The else-if chain would grow without bound and hit V8's parser recursion
  // limit above ~10k routes; a single object lookup scales to any route count.
  // Below STATIC_MAP_THRESHOLD a short if/else chain with string equality is
  // equally fast, so we fall back to it to avoid the map-object overhead.
  {
    let staticCount = 0;
    for (const key in ctx.router.static) {
      if (ctx.router.static[key]?.methods) staticCount++;
    }
    if (staticCount >= STATIC_MAP_THRESHOLD) {
      const mapRef = buildStaticMap(ctx);
      if (mapRef) {
        if (ctx.opts?.matchAll) {
          // Iterate in insertion order so wildcard ("") and method-specific results
          // are collected in the same relative order as the original if/else codegen.
          code += `const _sp=${mapRef}[p];if(_sp){for(const _sk in _sp){if(_sk===""||_sk===m)r.unshift(_sp[_sk]);}}`;
        } else {
          code += `const _sp=${mapRef}[p];if(_sp){const _sr=_sp[m]??_sp[""];if(_sr)return _sr;}`;
        }
      }
    } else {
      // Fallback: short if/else chain — faster for very small route tables.
      let hasIf = false;
      for (const key in ctx.router.static) {
        const node = ctx.router.static[key];
        if (node?.methods) {
          code += `${hasIf ? "else " : ""}if(p===${JSON.stringify(key.replace(/\/$/, "") || "/")}){${compileMethodMatch(ctx, node.methods, [], -1)}}`;
          hasIf = true;
        }
      }
    }
  }

  // Trie traversal starts at position 0 — the character index before the leading '/'
  // in the path string `p`. Each charCodeAt check advances through the string.
  const match = compileTrieNode(ctx, ctx.router.root, [], 0);
  if (match) {
    code += `const len=p.length;${match}`;
  }

  if (!code) {
    return ctx.opts?.matchAll ? `return [];` : "";
  }

  const normalizeHelper = code.includes("_normalizeGroups(")
    ? `const _prefix=${JSON.stringify(UNNAMED_GROUP_PREFIX)},_prefixLen=${UNNAMED_GROUP_PREFIX.length};const _normalizeGroups=(g)=>{if(!g)return g;for(const k in g){if(k.startsWith(_prefix)){g[k.slice(_prefixLen)]=g[k];delete g[k]}}return g;};`
    : "";

  const normalizePathHelper = ctx.opts?.normalize
    ? `if(p.includes("/.")){let _r=[];for(let _v of p.split("/")){if(_v===".")continue;_v===".."&&_r.length>1?_r.pop():_r.push(_v)}p=_r.join("/")||"/"}`
    : "";

  return `${ctx.opts?.matchAll ? `let r=[];` : ""}${normalizeHelper}${normalizePathHelper}if(p[p.length-1]==="/")p=p.slice(0,-1)||"/";${code}${ctx.opts?.matchAll ? "return r;" : ""}`;
}

// absentParam: when true, only include matchers whose last paramsMap entry is optional.
// wildcardBoundary: when set, required wildcards get a len>boundary guard.
function compileMethodMatch(
  ctx: CompilerContext,
  methods: Record<string, MethodData<any>[] | undefined>,
  params: string[],
  currentIdx: number,
  absentParam?: boolean,
  wildcardBoundary?: TriePos,
): string {
  let code = "";
  for (const key in methods) {
    const matchers = methods[key];
    if (!matchers || matchers.length === 0) continue;

    // absentParam filter: only include routes whose last param (index 2 = optional flag) is true.
    const filtered = absentParam
      ? matchers.filter((m) => m.paramsMap?.[m.paramsMap.length - 1]?.[2] /* optional */)
      : matchers;
    if (filtered.length === 0) continue;

    if (key !== "") code += `if(m==="${key}")${filtered.length > 1 ? "{" : ""}`;
    const _matchers = filtered
      .map((m) => compileFinalMatch(ctx, m, currentIdx, params, wildcardBoundary))
      .sort((a, b) => b.weight - a.weight);
    for (const matcher of _matchers) {
      code += matcher.code;
    }
    if (key !== "") code += filtered.length > 1 ? "}" : "";
  }
  return code;
}

function compileFinalMatch(
  ctx: CompilerContext,
  data: MethodData<any>,
  _currentIdx: number,
  params: string[],
  wildcardBoundary?: TriePos,
): { code: string; weight: number } {
  let ret = `{data:${serializeData(ctx, data.data)}`;

  const conditions: string[] = [];

  // Add param properties
  const { paramsMap, paramsRegexp } = data;
  if (paramsMap && paramsMap.length > 0) {
    // For required (named) wildcards: ensure the wildcard segment is non-empty.
    // paramsMap entry: [segmentIndex, nameOrRegexp, optional(index 2)]
    if (wildcardBoundary !== undefined && !paramsMap[paramsMap.length - 1][2] /* optional */) {
      conditions.push(`len>${posStr(wildcardBoundary)}`);
    }
    // Check regexp constraints using paramsMap-indexed param expressions.
    for (let j = 0; j < paramsMap.length; j++) {
      const regexp = paramsRegexp[paramsMap[j][0]];
      if (!regexp) continue;
      conditions.push(`${regexp.toString()}.test(${params[j]})`);
    }

    // Create the param object based on captured param expressions.
    ret += ",params:{";
    for (let i = 0; i < paramsMap.length; i++) {
      const map = paramsMap[i];
      ret +=
        typeof map[1] === "string"
          ? `${JSON.stringify(map[1])}:${params[i]},`
          : `..._normalizeGroups((${map[1].toString()}.exec(${params[i]}))?.groups),`;
    }
    ret += "}";
  }

  const code =
    (conditions.length > 0 ? `if(${conditions.join("&&")})` : "") +
    (ctx.opts?.matchAll ? `r.unshift(${ret}});` : `return ${ret}};`);

  return { code, weight: conditions.length };
}

function serializeData(ctx: CompilerContext, value: any): string {
  if (ctx.compileToString) {
    if (ctx.opts?.serialize) {
      value = ctx.opts.serialize(value);
    } else if (typeof value?.toJSON === "function") {
      value = value.toJSON();
    } else {
      value = JSON.stringify(value);
    }
  }
  let index = ctx.data.indexOf(value);
  if (index === -1) {
    ctx.data.push(value);
    index = ctx.data.length - 1;
  }
  return `$${index}`;
}

// Build the static-route map used by compileRouteMatch.
// In JIT mode an actual null-prototype object is pushed to ctx.data so it can be
// passed as a function argument.  In toString mode a self-contained code expression
// is pushed so it can be inlined as `const $N = ...`.
// Returns the data reference string (e.g. "$0"), or null when there are no static routes.
function buildStaticMap(ctx: CompilerContext): string | null {
  if (!ctx.router.static) return null;

  if (!ctx.compileToString) {
    // JIT mode ---------------------------------------------------------------
    const map: Record<string, Record<string, { data: any }>> = Object.create(null);
    for (const key in ctx.router.static) {
      const node = ctx.router.static[key];
      if (!node?.methods) continue;
      const path = key.replace(/\/$/, "") || "/";
      const methodMap: Record<string, { data: any }> = Object.create(null);
      for (const method in node.methods) {
        const matchers = node.methods[method];
        if (!matchers?.length) continue;
        methodMap[method] = { data: matchers[0].data };
      }
      if (Object.keys(methodMap).length) map[path] = methodMap;
    }
    if (!Object.keys(map).length) return null;
    const idx = ctx.data.length;
    (ctx.data as any[]).push(map);
    return `$${idx}`;
  } else {
    // toString mode ----------------------------------------------------------
    // Serialize each data value first (so their $N refs have lower indices than
    // the map itself), then build the map expression referencing those $N vars.
    // Because ctx.data entries are emitted as a single `const $0=…,$1=…,…`
    // declaration, later entries may reference earlier ones.
    const pathEntries: string[] = [];
    for (const key in ctx.router.static) {
      const node = ctx.router.static[key];
      if (!node?.methods) continue;
      const path = key.replace(/\/$/, "") || "/";
      const methodEntries: string[] = [];
      for (const method in node.methods) {
        const matchers = node.methods[method];
        if (!matchers?.length) continue;
        const dataRef = serializeData(ctx, matchers[0].data);
        methodEntries.push(`${JSON.stringify(method)}:{data:${dataRef}}`);
      }
      if (methodEntries.length) {
        pathEntries.push(`${JSON.stringify(path)}:{${methodEntries.join(",")}}`);
      }
    }
    if (!pathEntries.length) return null;
    // Object.assign copies only own enumerable properties from the object
    // literal into the null-prototype target, so the result is a pure
    // dictionary with no inherited keys — identical to what the JIT path
    // builds at runtime.
    const mapExpr = `Object.assign(Object.create(null),{${pathEntries.join(",")}})`;
    const idx = ctx.data.length;
    ctx.data.push(mapExpr);
    return `$${idx}`;
  }
}
